export const CONTENT_FEATURES = 'CONTENT_FEATURES';
export const CONTENT_LISTEN = 'CONTENT_LISTEN';
export const CONTENT_DOWNLOAD = 'CONTENT_DOWNLOAD';
export const CONTENT_CONTACT = 'CONTENT_CONTACT';